### ISSUE TITLE
Code Formatting Keep Duplicating Last Line When `meson.build` Has Fewer Lines

### ISSUE THREAD

**Issue by GreenYun** [JCWasmx86/mesonlsp#101]
**Describe the bug**
Code formatting duplicates last line of `meson.build` with VS Code 'Format On Save' on.

**To Reproduce**

1. Make an empty directory, and add this `meson.build` file into.

```meson
project('test', 'c')
subdir('lib')
```

2. Optionally, "mkdir" the lib directory and put this `meson.build` file into.

```meson
sources = [
    'source.c'
]
```

**Expected behavior**
The 'meson.build' files should not be changed because they are well formatted.

**Screenshots/Screencasts**
In this video, everytime the code was changed without editing is because "Command+s" ("save" on macOS) pressed.

https://github.com/JCWasmx86/mesonlsp/assets/26381267/c0013761-cec6-4f39-9109-b8911791fd00

https://github.com/JCWasmx86/mesonlsp/assets/26381267/5a48ef8d-e9f9-4deb-89d3-de82edf78ff6

**System info**
 - OS: macOS 12.7.5
 - Editor: VS Code 1.91.0-insider
 - Version: mesonlsp 4.2.2 x86-64 apple darwin (downloaded binary from GitHub release)

**Additional context**
muon is not installed thus the formatter should be mesonlsp integrated. Also, by disabling mesonlsp will solve the problem.

**Comment by JCWasmx86** [comment]
Should be fixed and in the next release.
