### ISSUE TITLE
Subproject check does not understand f-strings

### ISSUE THREAD

**Issue by QuLogic** [JCWasmx86/mesonlsp#114]
**Describe the bug**
In Matplotlib, we have a `subproject` call that uses an f-string with a version:
https://github.com/matplotlib/matplotlib/blob/main/extern/meson.build#L19-L21
With `mesonlsp`, this produces a warning:
```
Unknown subproject `freetype-@LOCAL_FREETYPE_VERSION@`
```

**To Reproduce**
1. Clone https://github.com/matplotlib/matplotlib
2. Open `extern/meson.build`
3. Go to line 19
4. See error noted above.

**Expected behavior**
No warning, as there is a subproject for the evaluated string, i.e. if I replace the substitution with a hard-coded string, then `mesonlsp` stops complaining.

**System info**
 - OS: Fedora, from your COPR
 - Editor: neovim 0.10.0
 - Version: 4.3.1

**Comment by JCWasmx86** [comment]
I implemented it quickly. It works as long as there is only one variable.
