### ISSUE TITLE
Subproject variables are not found

### ISSUE THREAD

**Issue by ptomato** [JCWasmx86/mesonlsp#126]
**Describe the bug**
No matter what argument I pass to `subproject.get_variable()`, the language server always notes a problem: "Unable to find variable ___ in subproject ___".

**To Reproduce**
1. Clone https://gitlab.gnome.org/ptomato/gjs.git
2. Check out commit `65b5fa5d0d1dda17301e8ac751f32dc46a575e52`
3. Open the project in VSCodium
4. Open `installed-tests/js/meson.build` and look at line 72
5. See errors:

> Unable to find variable gimarshallingtests_typelib in subproject gobject-introspection-tests [Ln 72, Col 5]
> Unable to find variable regress_typelib in subproject gobject-introspection-tests [Ln 73, Col 5]
> Unable to find variable warnlib_typelib in subproject gobject-introspection-tests [Ln 74, Col 5]

**Expected behavior**
The language server should be able to look into the subproject's meson.build file and find the variables.

**Screenshots/Screencasts**
N/A

**System info**
 - OS: Linux, Fedora Linux 40.20240727.0 (Silverblue), mesonlsp installed automatically inside VSCodium
 - Editor: VSCodium installed from Flatpak
 - Version: 1.91.1

**Additional context**
N/A

**Comment by JCWasmx86** [comment]
Seems to be a problem with tree-sitter-ini.


At least my diagnostics should be better, if a wrap file is not parseable

**Comment by JCWasmx86** [comment]
Thanks you for this issue. Wrap setup errors are now propagated to the editor instead of just being logged. The problem was a bug in tree-sitter-ini that's now fixed. The next release will have this issue fixed. It still cannot find those variables:
```
installed-tests/js/meson.build[23:23] 🔴  Unable to find variable test_regress_sources in subproject gobject-introspection
installed-tests/js/meson.build[24:8] 🔴  Unable to find variable test_regress_headers in subproject gobject-introspection
installed-tests/js/meson.build[26:8] 🔴  Unable to find variable test_marshalling_sources in subproject gobject-introspection
installed-tests/js/meson.build[27:8] 🔴  Unable to find variable test_marshalling_headers in subproject gobject-introspection
installed-tests/js/meson.build[28:23] 🔴  Unable to find variable test_warnlib_sources in subproject gobject-introspection
installed-tests/js/meson.build[29:8] 🔴  Unable to find variable test_warnlib_headers in subproject gobject-introspection
installed-tests/js/meson.build[30:23] 🔴  Unable to find variable test_regress_incdirs in subproject gobject-introspection
```
But I cannot find them either here: https://gitlab.gnome.org/search?search=test_regress_headers&nav_source=navbar&project_id=659&group_id=8&search_code=true&repository_ref=main

**Comment by ptomato** [comment]
Thank you for the quick fix!

If you checked out the main branch of the project, those variables are indeed unable to be found. If you check out `65b5fa5d0d1dda17301e8ac751f32dc46a575e52` you should be on a branch where there should be no unfound variables.
