### ISSUE TITLE
Document link for subdir()

### ISSUE THREAD

**Issue by Freed-Wu** [JCWasmx86/mesonlsp#131]
**Is your feature request related to a problem? Please describe.**
`subdir("XXX")` will provide a document link to `XXX/meson.build`

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Will you write a patch?**

**Will you maintain it, if you submit a patch?**

**Additional context**

**Comment by JCWasmx86** [comment]
It already works


https://github.com/user-attachments/assets/fed203ac-c126-40b9-a3ed-d03cd295d66f

And please try to follow the template the next time

**Comment by JCWasmx86** [comment]
No response/clarification. Closing

**Comment by Freed-Wu** [comment]
I use mesonlsp 4.3.3. Does this feature belong next version?

**Comment by JCWasmx86** [comment]
It's already implemented since 4.0.0

**Comment by Freed-Wu** [comment]
It is realized as gotoDefintion, not DocumentLink

**Comment by JCWasmx86** [comment]
It currently works fine, what's the advantage of implementing it with document links? Please follow the issue template

**Comment by Freed-Wu** [comment]
Document link can allow user display the URL. For example clangd realize `#include` as gotoDefinition and Document link.

![Screenshot from 2024-08-27 22-52-47](https://github.com/user-attachments/assets/bb647736-2609-46a1-bd59-c9ae2a909607)

**Comment by JCWasmx86** [comment]
I won't implement it, due to missing time, but patches are welcome
