### ISSUE TITLE
Doubts about dependencies

### ISSUE THREAD

**Issue by tesseract241** [JCWasmx86/mesonlsp#136]
I see that the mesonlsp.spec file includes as dependencies patch, git, mercurial and subversions, but as far as I understand it these are actually only used by meson wrap and maybe for testing, not to actually run mesonlsp.  
These dependencies are in turn inherited by the archlinux extra repository.  
Could  they be moved to the build dependencies instead?

**Comment by JCWasmx86** [comment]
Well, they are runtime dependencies, so I think the location makes sense

**Comment by tesseract241** [comment]
Oh, I missed 
> Automatic subproject/wrap downloads

in the features, it makes more sense now. 
Thanks.
