### ISSUE TITLE
COPR build is skipping aarch64 builds

### ISSUE THREAD

**Issue by 1ace** [JCWasmx86/mesonlsp#141]
**Describe the bug**

Looking at the latest build for instance: https://copr.fedorainfracloud.org/coprs/jcwasmx86/Swift-MesonLSP/build/8034049/
The two `x86_64` builds have "succeeded", while the two `aarch64` builds were "skipped".

This can be confirmed by looking at the artifacts available for the two `fedora-$releasever-aarch64` in https://download.copr.fedorainfracloud.org/results/jcwasmx86/Swift-MesonLSP/; they contain nothing.

**Expected behavior**

The aarch64 builds should not be disabled/skipped/etc. so that those of us on an ARM laptop get to use `mesonlsp` too :P

**Additional context**

Building it by hand (`meson setup` + `meson compile`) yields a working binary, so there is no need to disable aarch64 in case it was thought to be non-functional :)

*(I deleted the other sections as they are only relevant if the bug is in mesonlsp itself)*

**Comment by JCWasmx86** [comment]
Hey, thank you for this issue! I'm not sure why it was skipped, but I will investigate it

**Comment by JCWasmx86** [comment]
It took a while, but if this works: https://copr.fedorainfracloud.org/coprs/jcwasmx86/Swift-MesonLSP/build/8062051/ you will have fancy aarch64 builds :)


I hope it's not inappropriate to ask: Have you already used mesonlsp somewhat extensively? If yes, do you have a few spare seconds to fill out this survey/telemetry information: https://github.com/JCWasmx86/mesonlsp/discussions/104

**Comment by JCWasmx86** [comment]
It seems like the build completed successfully

**Comment by 1ace** [comment]
Thanks! I installed it (and deleted my local build), and I can confirm it works :+1:

> I hope it's not inappropriate to ask: Have you already used mesonlsp somewhat extensively? If yes, do you have a few spare seconds to fill out this survey/telemetry information: #104

I have discovered this project on friday and I tried it for the first time this morning, just before posting this issue, and I haven't worked on meson files today (other than just discovering what the lsp provides here for a few minutes), so I wouldn't exactly call my use "extensive" 😅

I'll post something on #104 now, and try to remember to come back once I have more feedback 🙂
