### ISSUE TITLE
Can't resolve symbols coming from subdir if the path depends on cross-files if used in VSCode

### ISSUE THREAD

**Issue by danielefaugiana** [JCWasmx86/mesonlsp#18]
**Describe the bug**
If the meson.build file contains a subdir(path) where path depends on some value coming from a cross file, the language server will not be able to resolve this symbol and therefore will flag the symbols as "Unknown Identifiers".

**To Reproduce**
1. Clone https://github.com/danielefaugiana/auser
2. Open the project in Visual Studio Code
3. Check the top level Meson file, see the arch_src, arch_include and kernel_linker_script variables are flagged

**Expected behavior**
All symbols are resolved taking the information from the default build directory as set in Visual Studio Code's Meson Options.
The build directory contains the configuration information in meson-info so this information should be available.

**Screenshots/Screencasts**
![image](https://github.com/JCWasmx86/Swift-MesonLSP/assets/109464019/602612d9-cce9-461d-b5f6-12000e421222)

**System info**
 - OS: Ubuntu 23.10, language server installed through Visual Studio Code
 - Editor: Visual Studio Code with Meson extension v1.12.1
 - Version: 1.83.1 (VSCode)

**Comment by JCWasmx86** [comment]
Thanks for the detailed bugreport, I pushed a new commit to main that should fix that.

![image](https://github.com/JCWasmx86/Swift-MesonLSP/assets/63594136/8bd78b35-d74c-4fa8-99aa-daaf3ab68c97)

Feel free to reopen this issue (or preferable create a new issue), if you encounter similar porblems, as the part guessing possible values for `subdir(x)` where x is not a constant string is really just guessing+heuristics

**Comment by danielefaugiana** [comment]
Thanks a lot that was very fast!
Looking forward to being able to grab the next release.

**Comment by JCWasmx86** [comment]
You can try it out in the most recent VSCode extension release

**Comment by danielefaugiana** [comment]
It works!

**Comment by JCWasmx86** [comment]
Great to hear :)
