### ISSUE TITLE
Weird COPR versioning

### ISSUE THREAD

**Issue by ferdnyc** [JCWasmx86/mesonlsp#19]
I was just looking at the Meson VSCode extension, as well as the COPR packages for Swift-MesonLSP, and I was initially confused why the extension is using version 3.0.5, while the COPR packages are only at version 0.0.34.

Then I realized that the Version and Release fields of the COPR packaging are backwards. As the [Fedora Packaging Guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines) outline in [the Versioning Guidelines section](https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/) (emphasis added):
> Fedora’s package versioning scheme encompasses both the `Version:` and `Release:` tags, as well as `Epoch:`. The overriding goal is to provide sequences of packages which are treated as updates by RPM’s version comparison algorithm while accommodating varied and often inconsistent upstream versioning schemes.
> 
> **The `Version:` field contains the upstream project version, and the `Release:` field specifies the downstream release number.**

Fortunately, since 3.0.5 is (much) higher than 0.0.34, version-comparison-wise, swapping the fields around and creating a `Swift-MesonLSP-3.0.5-0.1.x86_64.rpm` package would be no problem, as it would be parsed as an upgrade to any of the current 0.0.* packages.

**Comment by JCWasmx86** [comment]
This was the time I just did `mv docs /dev/null`. I will address it in the next release (So probably 3.0.7)
