### ISSUE TITLE
error report of str.splitlines()

### ISSUE THREAD

**Issue by ZZH-Finalize** [JCWasmx86/mesonlsp#30]
**Describe the bug**
LSP report a problem on str.splitlines(), but str does have this method.

![image](https://github.com/JCWasmx86/Swift-MesonLSP/assets/33342565/892eb56d-2f80-4f4e-94eb-1cc7c4d44710)
![image](https://github.com/JCWasmx86/Swift-MesonLSP/assets/33342565/da6dc458-11ea-45bf-b94b-6751f45210a2)

**Comment by JCWasmx86** [comment]
Thanks a lot for the bug report. It will be fixed in the next version
