### ISSUE TITLE
libdrm meson causes SIGILL / auto-killed by vscode

### ISSUE THREAD

**Issue by shoffmeister** [JCWasmx86/mesonlsp#31]
**Describe the bug**

Trying to use the extension on the meson build configuration for libdrm, the extension goes into a crash-loop, see below:

```
[ INFO ] Downloading WrapDB data from https://wrapdb.mesonbuild.com/v2/releases.json
[ INFO ] Executing "'curl' 'https://wrapdb.mesonbuild.com/v2/releases.json' '-o' '/tmp/89B9C07E-3CD0-4BDC-AA80-194D42AA60EC' '-s' '-L'" at ???
[ INFO ] Connected with client Visual Studio Code 1.84.2
[ INFO ] Renaming is disabled as it is broken outside of GNOME Builder. Use GNOME Builder for an optimal experience.
[ INFO ] Swift-MesonLSP is licensed under the terms of the GNU General Public License v3.0
[ INFO ] Need help? - Open a discussion here: https://github.com/JCWasmx86/Swift-MesonLSP/discussions or join https://matrix.to/#/#mesonlsp:matrix.org
[ INFO ] No subprojects directory found
[ INFO ] Setup all directories for subprojects
[ INFO ] Setup all subprojects, rebuilding tree (If there were any found)
[Error - 9:30:26 AM] Server process exited with signal SIGILL.
[Error - 9:30:26 AM] The Meson Language Server (Swift-MesonLSP) server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

Part of earlier error context is this:
```
[ ERROR ] ResponseError(code: LanguageServerProtocol.ErrorCode(rawValue: -32601), message: "Unhandled method window/workDoneProgress/create")
...
[ ERROR ] Error during sleeping: CancellationError()
[ INFO ] Cancelling parsing - After sleeping
...
[ INFO ] Version = >= 0.59
[ INFO ] Publishing 3 diagnostics for /home/stefan/gitlab.freedesktop.org/mesa/drm/tests/tegra/meson.build
[ WARNING ] Unused assignment
[ WARNING ] Unused assignment
[ WARNING ] Unused assignment
...
```

I cannot tell whether `tests/tegra/meson.build` is part of the problem, or whether this is just the extension being unhappy with itself.

**To Reproduce**
1. install extension into Visual Studio Code (latest == 1.84.2)
2. git clone https://gitlab.freedesktop.org/mesa/drm
3. open cloned repository in Visual Studio Code
4. open `tests/tegra/meson.build`
5. See error

**Expected behavior**
No SIGILL, no crash-loop.

**System info**
 - OS: Fedora Linux 39, x64_86, extension from Microsoft Marketplace
 - Editor: Visual Studio Code (latest == 1.84.2)
 - Version: mesonbuild.mesonbuild v1.18.1 (2023-11-17, 17:38:30)

**Comment by JCWasmx86** [comment]
Thanks a lot for that bug report. Sadly I can't reproduce that. Can you please give me the entire output? Theoretically there should be a backtrace in there. (Maybe interleaved with the other output)

If there is really no backtrace, could you please use `coredumpctl` to get backtraces? The executable has full debuginfo included

**Comment by shoffmeister** [comment]
```
stefan@fedora:~$ coredumpctl info 
           PID: 5559 (Swift-MesonLSP)
           UID: 1000 (stefan)
           GID: 1000 (stefan)
        Signal: 4 (ILL)
     Timestamp: Sun 2023-11-19 09:30:26 CET (3h 21min ago)
  Command Line: /home/stefan/.config/Code/User/globalStorage/mesonbuild.mesonbuild/lsp/Swift-MesonLSP --lsp
    Executable: /home/stefan/.config/Code/User/globalStorage/mesonbuild.mesonbuild/lsp/Swift-MesonLSP
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-code-377c17cbb6da4ab288de13164d154474.scope
          Unit: user@1000.service
     User Unit: app-code-377c17cbb6da4ab288de13164d154474.scope
         Slice: user-1000.slice
     Owner UID: 1000 (stefan)
       Boot ID: e9fc31a258054533b7134bcaa4d6591d
    Machine ID: 38597d41642543e2931606f64d1dea66
      Hostname: fedora
       Storage: /var/lib/systemd/coredump/core.Swift-MesonLSP.1000.e9fc31a258054533b7134bcaa4d6591d.5559.1700382626000000.zst (present)
  Size on Disk: 11.4M
       Message: Process 5559 (Swift-MesonLSP) of user 1000 dumped core.
                
                Module /home/stefan/.config/Code/User/globalStorage/mesonbuild.mesonbuild/lsp/Swift-MesonLSP without build-id.
                Module /home/stefan/.config/Code/User/globalStorage/mesonbuild.mesonbuild/lsp/Swift-MesonLSP
                Stack trace of thread 5584:
                #0  0x000055b522c50c24 n/a (/home/stefan/.config/Code/User/globalStorage/mesonbuild.mesonbuild/lsp/Swift-MesonLSP + 0x6d5c24)
                #1  0x0000000000000000 n/a (n/a + 0x0)
                ELF object binary architecture: AMD x86-64
```

resolving to

```
[Thread debugging using libthread_db enabled]                                                                                                                                                                      
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/home/stefan/.config/Code/User/globalStorage/mesonbuild.mesonbuild/lsp/Swift-Me'.
Program terminated with signal SIGILL, Illegal instruction.
#0  Swift runtime failure: Unexpectedly found nil while unwrapping an Optional value () at /home/runner/work/Swift-MesonLSP/Swift-MesonLSP/Sources/LanguageServer/MesonServer.swift:1081
1081    /home/runner/work/Swift-MesonLSP/Swift-MesonLSP/Sources/LanguageServer/MesonServer.swift: No such file or directory.
[Current thread is 1 (Thread 0x7f37437fe6c0 (LWP 5584))]
```

I did not see a backtrace inside the "normal" Visual Studio Code output.

Looking at https://github.com/JCWasmx86/Swift-MesonLSP/blob/e9733cc7226f766384c39d26d26ebbe37fa32868/Sources/LanguageServer/MesonServer.swift#L1081 would indeed serve to explain the error, but somehow makes the root cause not all that much clearer...

I did not mention in my repro instructions to set up a build environment following the documentation; here is what I did (as far as I recollect):
```
    meson builddir/
```
After that, I twiddled with some `description` in `meson_options.txt`, but that's about it as far as the build system is concerned.

For the record, this is a relatively bare-bones Fedora Linux 39 inside VMWare Workstation; it only contains things to get `fedpkg` (and vscode) running - that is largely the Fedora RPM package build environment. I doubt that makes any difference to the error, tough.

**Comment by JCWasmx86** [comment]
Thanks. That helped. I think that's some race-condition. That's why I probably can't reproduce it. I pushed a patch on `main`. Could you please test it? (Just compile it using `make&&sudo make install` or grab it from GH Actions). VSCode will prefer Swift-MesonLSP on the PATH over the built-in one.

**Comment by shoffmeister** [comment]
Many thanks for the very fast reaction!

I took the F39 binaries off GH actions and put them on the PATH. I no longer see errors and vscode does not force-disable the extension any more. Great!

May I suggest adding logging to the extension, printing the location of the binary in use? This would remove any lingering doubt as to whether I _really_ am using the right binary? Right now I see
```
stefan@fedora:~/bin$ ps -ef | grep -i meson
stefan      2871    2783  0 14:19 ?        00:00:00 /home/stefan/.config/Code/User/globalStorage/mesonbuild.mesonbuild/lsp/Swift-MesonLSP --lsp
```
which would suggest to me that I am not using what I put on the PATH
```
stefan@fedora:~$ whereis Swift-MesonLSP
Swift-MesonLSP: /home/stefan/bin/Swift-MesonLSP

stefan@fedora:~$ whereis Swift-MesonLSP.debug 
Swift-MesonLSP.debug: /home/stefan/bin/Swift-MesonLSP.debug
```

**Comment by JCWasmx86** [comment]
> I took the F39 binaries off GH actions and put them on the PATH. I no longer see errors and vscode does not force-disable the extension any more. Great!

Sound's great!


No, that's sadly not the right binary.

You could try to remove the `/home/stefan/.config/Code/User/globalStorage/mesonbuild.mesonbuild/lsp` folder and restart VSCode. If the extension downloads the language server again, maybe the PATH passed to VSCode is wrong. As a last resort, you could just swap `/home/stefan/.config/Code/User/globalStorage/mesonbuild.mesonbuild/lsp/Swift-MesonLSP` with `Swift-MesonLSP` you just downloaded.

**Comment by shoffmeister** [comment]
```
rm -rf /home/stefan/.config/Code/User/globalStorage/mesonbuild.mesonbuild/lsp
```
convinced vscode to pick the right LSP binary :)

I can (re)confirm that I no longer get any reports of SIGILL, this time with the right binary.

As you mention fixing a race-condition:

I have a faint recollection of the LSP misbehaving erratically, which would align well with your intent for adjustment. I was somewhat focused on addressing some subtle C code, though, VM-rebooting every five minutes, so my recollection of matters around the build system integration into vscode is somewhat dim - sorry!

For reference, this machine has an Intel 11800H CPU, all its 16 sort-of-CPUs assigned to the VM, memory to no end.

**Comment by JCWasmx86** [comment]
Ok, so I guess if it can't be reproduced with the most recent binaries, I guess we can close this issue.

> I have a faint recollection of the LSP misbehaving erratically,[...]

Can you please give a bit more context regarding this statement?

**Comment by shoffmeister** [comment]
> > I have a faint recollection of the LSP misbehaving erratically,[...]
> 
> Can you please give a bit more context regarding this statement?

SIGILL. Really that only, and I only noticed because vscode complained about the repeated SIGILL and toast-notified about disabling the LSP.

My apologies for having been imprecise!

**Comment by JCWasmx86** [comment]
No worries. If you get SIGILL again, please reopen this issue
