### ISSUE TITLE
Crashing when viewing a diff in VSCode

### ISSUE THREAD

**Issue by tristan957** [JCWasmx86/mesonlsp#32]
**Describe the bug**
Server crashes when viewing a diff in VSCode.

**To Reproduce**
Open a diff in VSCode like what I did.

**Expected behavior**
Don't crash

**Screenshots/Screencasts**
![image](https://github.com/JCWasmx86/Swift-MesonLSP/assets/11936772/662c0444-1ac5-4a96-a814-4fc6bdba445d)

**System info**
 - OS: Fedora 39 (COPR)
 - Editor: VSCode
 - Version: 3.1.2

**Comment by tristan957** [comment]
```
$ Swift-MesonLSP --version
Error: Unknown option '--version'
Usage: meson-lsp [<options>] [<paths> ...]
  See 'meson-lsp --help' for more information.
```

binary name also seems to be wrong here...

**Comment by tristan957** [comment]
Received signal 4. Backtrace:
0x55d562d274b2
0x55d562d27727
0x7f25c125c99f
0x55d562f42255
0x55d563922dcd
0x55d5639234ab
0x55d5638e9333
0x55d5638e90e1
0x55d5638f4bc1
0x7f25c12ac896
0x7f25c13336bb
0xffffffffffffffff
[Error - 2:50:01 PM] Server process exited with signal SIGILL.

**Comment by tristan957** [comment]
Would be nice to include debug symbols in the binary.

**Comment by JCWasmx86** [comment]
I've fixed the binary name. I have an idea. why it is crashing, but I have no idea, why there is no debuginfo in the COPR.

I used
```
%global debug_package %{nil}
```
This should work (I think).

**Comment by JCWasmx86** [comment]
Is fixed in the C++ rewrite
