### ISSUE TITLE
you should try to find it from environment variables here, otherwise it will cause an Error

### ISSUE THREAD

**Issue by PterX** [JCWasmx86/mesonlsp#41]
https://github.com/JCWasmx86/Swift-MesonLSP/blob/ae571ffcb8573879b1637edf15a74130437e8e47/Sources/LanguageServer/MesonServer.swift#L80

**Comment by JCWasmx86** [comment]
Thanks. That will be addressed in the the C++-Rewrite (#36)

**Comment by PterX** [comment]
> Thanks. That will be addressed in the the C++-Rewrite (#36)

Thx
