### ISSUE TITLE
`default_options` accepts a dictionary since meson 1.2.0

### ISSUE THREAD

**Issue by GreenYun** [JCWasmx86/mesonlsp#48]
**Describe the bug**
`default_options` accepts a dictionary since meson 1.2.0. Swift-MesonLSP only changed the AST on `project` function, while `dependency` and `subproject` also have `default_options`.

**To Reproduce**
1. Make a demo `meson.build` file like:

```meson
project('demo', 'c', default_options: {'c_std': 'c11'})
subproject('subdemo', default_options: {'c_std': 'c17'})
dependency('libdep', default_options: {'some_feature': 'enabled'})
```

2. Swift-MesonLSP will return error on the last two lines:

```
Expected list(str), got dict(str)
```

**Expected behavior**
Not reporting the errors.

**Screenshots/Screencasts**
N/A

**System info**
 - OS: Debian 12, Swift-MesonLSP installed from swift-mesonlsp-apt-repo
 - Editor: VSCode
 - Version: 3.1.3

**Additional context**

**Comment by JCWasmx86** [comment]
Thanks a lot for this issue.

This will be fixed by the C++-Rewrite. You can grab a binary from Github Actions and drop it into the current location of Swift-MesonLSP.

And one important notice: swift-mesonlsp-apt-repo will be discontinued, as it's too much work for me to provide .deb files for 3 Ubuntu and 3 Debian versions.

**Comment by JCWasmx86** [comment]
@GreenYun Feel free to try the binary here: https://github.com/JCWasmx86/Swift-MesonLSP/releases/tag/v3.1.4 It won't end up in the apt repo, but you can replace the binary manually

**Comment by ghost** [comment]
@JCWasmx86 Is that release the version written in `swift`? Isn't there a `c++` port binary to try?

**Comment by JCWasmx86** [comment]
Yes, that's a Swift version, if you want to use the C++-Version, you can grab a binary from here: https://github.com/JCWasmx86/Swift-MesonLSP/actions/runs/8145641394 (Or wait for: https://github.com/JCWasmx86/Swift-MesonLSP/actions/runs/8159074154 to finish, especially if you are on Windows)

1. Use the alpine static binary (The macOS support is more like beta, windows is currently only tested in the CI => alpha)
2. Rename it to Swift-MesonLSP and copy it into /usr/bin (Or wherever your current Swift-MesonLSP binary is)
3. Restart your editor
4. Congrats, you use the C++-Version now
5. (Not mandatory, but I would really appreciate your input) Please join https://matrix.to/#/#mesonlsp:matrix.org or use https://github.com/JCWasmx86/Swift-MesonLSP/discussions/10 for feedback. (Or you can DM me, either matrix, mastodon or discord)

**Comment by GreenYun** [comment]
> @GreenYun Feel free to try the binary here: https://github.com/JCWasmx86/Swift-MesonLSP/releases/tag/v3.1.4 It won't end up in the apt repo, but you can replace the binary manually


So grateful. I will have a try.

I have downloaded the C++ build (Debian sid) from GitHub action several days ago. Also, I upgraded my GCC to have latest libstdc++ support. It worked for me as well.


> 2. Rename it to Swift-MesonLSP and copy it into /usr/bin (Or wherever your current Swift-MesonLSP binary is)
> 3. Restart your editor
> 4. Congrats, you use the C++-Version now

This may not always work when remote developing with VSCode sometimes, which may need a full shutdown of VSCode server and kill all Swift-MesonLSP processes.
