### ISSUE TITLE
pre-commit-hooks support

### ISSUE THREAD

**Issue by Freed-Wu** [JCWasmx86/mesonlsp#65]
**Describe the solution you'd like**
Provide a `.pre-commit-hooks.yaml` to allow user use it to format and lint meson code.
That is, `mesonlsp` must have a CLI port to format and lint meson files.

TIA!

**Comment by JCWasmx86** [comment]
Duplicates #47 But If somebody wants explicit pre-commit support, they have to write a patch

**Comment by Freed-Wu** [comment]
Repeated with #47
