### ISSUE TITLE
Both apple architecture zip archives in the releases section are invalid

### ISSUE THREAD

**Issue by jasmith79** [JCWasmx86/mesonlsp#66]
Currently the apple darwin zip archives seem to be broken.

**To Reproduce**
1. Download the archive, e.g. `curl -OJ https://github.com/JCWasmx86/mesonlsp/releases/download/v4.1.8/mesonlsp-aarch64-apple-darwin.zip`
2. Attempt to unzip the archive `unzip mesonlsp-aarch64-apple-darwin.zip`
3. See error:

>  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of mesonlsp-aarch64-apple-darwin.zip or
        mesonlsp-aarch64-apple-darwin.zip.zip, and cannot find mesonlsp-aarch64-apple-darwin.zip.ZIP
, period.

**Expected behavior**
I expect the unarchiving to work. To test I ran through exactly the same steps with the gnu-windows zip file and it worked fine, although obviously is useless on a Mac.

**System info**
 - OS: MacOS Ventura 13.6.4 M1 and Sonoma 14.4.1 x64

**Additional context**
Windows zip archive works as expected, only the Mac releases seem impacted. I also tested at least the aarch zip archive back to 4.1.2, all were affected.

**Comment by JCWasmx86** [comment]
Weird. For me this command:
```
curl -OJ https://github.com/JCWasmx86/mesonlsp/releases/download/v4.1.8/mesonlsp-aarch64-apple-darwin.zip
```
just creates an empty file, if I add `-L` to the command it works :/

**Comment by jasmith79** [comment]
Weird. Github must be doing some sort of redirect. Anyway thanks for the help!
