### ISSUE TITLE
Duplicate entries in completions

### ISSUE THREAD

**Issue by hqnna** [JCWasmx86/mesonlsp#92]
**Describe the bug**
The language server generates duplicate entries when providing completions.

**To Reproduce**
1. Install vscode or any other editor with LSP support
2. Install mesonlsp to the `$HOME/.local/bin` directory
3. Ensure `$HOME/.local/bin` is in your `$PATH` first
4. Install the official meson extension and type out the `project` line
5. Notice how when typing `version` you see duplicate entries

**Expected behavior**
There should only be one entry for each lsp completion item when typing.

**Screenshots/Screencasts**
<img width="643" alt="image" src="https://github.com/JCWasmx86/mesonlsp/assets/46457601/6ac4ccd9-d5e8-444c-af46-bcdb3c19daef">
![image](https://github.com/JCWasmx86/mesonlsp/assets/46457601/ef297cf1-668a-4869-86d7-6702aab0fdbf)

**System info**
 - OS: macOS Sonoma 14.5
 - Editor: VSCode v1.88.1
 - Version: 4.2.2

**Additional context**
I was writing an extension for the [Zed](https://zed.dev) editor to add lsp and higlighting support for meson, when working on a hobby project with my own extension I noticed duplicates in that editor as well. I thought this might be some code in my extension so I commented out the bit of code used for adding color to suggestions, however even after removing said code and rebuilding the duplicate entry persisted. Given this seems to be persistent across multiple editors, extensions, and environments it seems to be a bug.

It should also be noted the first and second entries act different, with the first one being bugged.

https://github.com/JCWasmx86/mesonlsp/assets/46457601/0ccdbfd3-25e6-486c-aeba-10c1989999d1

**Comment by JCWasmx86** [comment]
Thanks for the bugreport. Weird, because for me it works on VSCode :(


[Screencast from 2024-05-30 13-57-31.webm](https://github.com/JCWasmx86/mesonlsp/assets/63594136/dd6b8ad3-eed3-4b64-b8cb-26ff8487d595)

![image](https://github.com/JCWasmx86/mesonlsp/assets/63594136/e2c8f435-2f43-4b6f-902a-4a69bdc39395)

**Comment by JCWasmx86** [comment]
I will try to setup Zed on Linux and checkout what happens

**Comment by JCWasmx86** [comment]
I think I could reproduce it, even with VSCode

**Comment by hqnna** [comment]
Completely unsure what's causing this, [my extension](https://github.com/hqnna/zed-meson) literally just downloads and runs the language server with the `--lsp` flag.. This is an extremely odd bug.

**Comment by hqnna** [comment]
So it appears the duplicate only appears in zed when im typing it *on the same line.*

https://github.com/JCWasmx86/mesonlsp/assets/46457601/660998de-5855-4906-b1ac-0f77b8c925ac

**Comment by JCWasmx86** [comment]
I think a fix will be there in the next few weeks, as I currently have a lot of other work to do :/ But feel free to investigate it yourself
